# Image modification triggered by CircleCI will start the deployment process
replicaCount: 3
image: grg1337/fintrack:front_app-main-20240711135614
imagePullSecrets: regcred
namespace: prod
service:
  type: ClusterIP
  port: 80
  targetPort: 43472
