variable "cluster_name" {}
variable "region" {}
variable "vpc_cidr" {}
variable "private_subnets" {}
variable "public_subnets" {}
variable "eks_version" {}
variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "dev_docdb_username" {}
variable "dev_docdb_password" {}
variable "stage_docdb_username" {}
variable "stage_docdb_password" {}
variable "prod_docdb_username" {}
variable "prod_docdb_password" {}
