# Image modification triggered by CircleCI will start the deployment process
replicaCount: 3
image: grg1337/fintrack:flask_auth_app-main-20240729121158
imagePullSecrets: regcred
namespace: prod
service:
  type: ClusterIP
  port: 80
  targetPort: 43482
secrets:
  name: prod-docdb-secret
