# It is safe to store the sealed secret in the git repository as it can be decrypted only by the cluster where it was created.
# Secrets can be sealed offline using the kubeseal CLI. To do so I created the SealedSecret with the predefined tls certificate.
# Secret with DocumentDB configuration for the dev environment.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: dev-docdb-secret
  namespace: dev
spec:
  encryptedData:
    db-password: AQBYeaT9u04RnOYVTBw2HqHg72HIFqUE5SM1Vca3yZKf9BBoATN59CKAIFFPgFGqACW1bqCEdlVz9MUl38O22pgoWYVd6b4bJrglWXCwcVx+3CI03K7Tkd2SCLO7k/RRFWqxfrZSSAzd0+fIvOrXoQLIzu9Y7kcliHecAydg932sSKcHRSIngZYsPDKFh19eguHAgQgJCwx3NXdLRMVzppBdaYud5YwdxakoImJhWCWikrirsknJtRLYfzHSqdNmXA2VxJLyEfQ9c5eFofxVP3hwdChllmn9R3tP04yAhkKTeZ1vVPuZ/hWZ+stOWjBNt72i5CloGLnh8u+DoeKNqhHHmFeMZ5cUeD4bb4kkXQ8SIQK4eEdNztYePMNkAkuF
    db-uri: AQB8QjbyhZd7Lai7q4mNZu6Rin+afwcLLTLeuGwfDIcsyjvzXsWwA26riVeKmlX77QLvjK/RdgKP1MX7847dlaSCODKm538Ibzhu6v5AhpjdefS2US5dz97RiaGZKz/NiLJce/Rt3M3kTIYnfaGpGPwpIE+1R1baC4xsMdxNY1Nzur3SHdV/ywCHRnkimyVIAMjaMOygw9KVyqdrXfgl0tLuendI7w6GiHuPoEEXR26nbvTks94emcNHgr1T2jA4qklqKChv177EYZacYMS5C0JdTISA58fOmmIC5sHYCORNTU9LJIb6Aun8noatHSrkt5R4C+Tc9Y/BPcS1foYB9j3Ysl2hQZj+PRyJLn+OqEdtijHY6imw96JznWV1Au1JdLQAjL39LjkWFnNU8E8E6KC0pkZ20LUHCAk+pzjyWN5RRmrQKJszmB/WG0chtZ4IVLJ8GKlQ
    db-username: AQBK7SDYQx6kQ3pOxkzbT7hxkSwojyMMvqIyCfRD4YrwU9XB4bC39d97gUqx+oZ2b5e8+uwYLtfVpMKHfLA3/iTJeY1evz8e2zHZSrr/7CJvCTOlcSGXCWXq17gmvhmwVOOAkmY8bh7mG02OnZfuC4vgkBWhHOJC9JzBONL74H4tneZL8EerZ8IywqvsBZZOA+tysCIvcpYzBqDeIzj4wYuE+sOKi5k9qjg0KVCSWCKzS03ews6C1+80YywP8m6KA954uXjIy8CRhRgVirsAqD8APKLe4Ldhh9LqNnWya71FKsM8pPToK87iFPjUWfodTlDXk5JUlO2/AxOkRJCLW/bJiCp6GMbELhb2u9iCOXbLSUrEUz9PXlWCZw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: dev-docdb-secret
      namespace: dev
