# This file is used to deploy the app-of-apps application in ArgoCD.
applications: 
 app-of-apps:
   namespace: argocd
   project: default
   source:
     repoURL: https://github.com/GrzegorzSychta/FinTrack.git
     targetRevision: main
     path: argo-cd-apps
   destination:
     server: https://kubernetes.default.svc
     namespace: argocd
   syncPolicy:
     automated:
       prune: true
       selfHeal: true
     syncOptions:
     - CreateNamespace=true